// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a ModelGenerator.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
namespace RDapter.Runner.Models
{
	//You can get Utilities package via nuget : Install-Package Deszolate.Utilities.Lite
	//[Utilities.Attributes.SQL.Table("DataScrapper")]
	public partial class DataScrapper
	{
		public string Query { get; set; }
		public string Content { get; set; }
		public string Platform { get; set; }
		public bool Sentiment { get; set; }
		public string Contextual { get; set; }
	}
}

