// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a ModelGenerator.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
namespace RDapter.Runner.Models
{
	//You can get Utilities package via nuget : Install-Package Deszolate.Utilities.Lite
	//[Utilities.Attributes.SQL.Table("TEST")]
	public partial class TEST
	{
		//[Utilities.Attributes.SQL.PrimaryKey]
		public int a { get; set; }
		public string b { get; set; }
	}
}

